### ISSUE TITLE
How many of his answers were right/wrong 

### ISSUE THREAD

**Issue by vardangrig** [0xe1f/ararat#15]
how to compare words

**Comment by 0xe1f** [comment]
`CrosswordView.state` will return a [CrosswordState](https://github.com/0xe1f/ararat/blob/master/library/src/main/java/org/akop/ararat/core/CrosswordState.kt) object, which you can interrogate for the information that you need.

**Comment by vardangrig** [comment]
thank's

**Comment by vardangrig** [comment]
I don't found the solution, can you help me?, I want to compare right answer with inputted word.

**Comment by 0xe1f** [comment]
[CrosswordState.charAt](https://github.com/0xe1f/ararat/blob/master/library/src/main/java/org/akop/ararat/core/CrosswordState.kt#L107) will let you access the contents of the square as input by user. [Crossword.cellMap](https://github.com/0xe1f/ararat/blob/master/library/src/main/java/org/akop/ararat/core/Crossword.kt#L72) will give you a 2D array of `Cell` objects in the original crossword, which you can then traverse and compare. Within each `Cell` object, [chars](https://github.com/0xe1f/ararat/blob/master/library/src/main/java/org/akop/ararat/core/Crossword.kt#L442) will give you the contents of the actual square.

**Comment by vardangrig** [comment]
sorry if I bore you, how can I find row and column in user inputted selected cell crosswordView.state?.charAt(row=?, column=?)

**Comment by 0xe1f** [comment]
Not sure if I understand you, but `row` is between 0 and height of the crossword. `column` is between 0 and width of the crossword. Return value of `charAt` will be null if the square is empty (user did not fill in) and non-null if it's been filled in.

**Comment by vardangrig** [comment]
i want to get my inputted letter to compare with right one,  
I don't know how to find CrosswordState.charAt() parameters

**Comment by 0xe1f** [comment]
Set up a nested loop that goes down and across the crossword - that will give you `row` and `column`. You can get width and height of the crossword [here](https://github.com/0xe1f/ararat/blob/master/library/src/main/java/org/akop/ararat/core/Crossword.kt#L33).
This is about as much as I can help regarding this specific issue.
