### ISSUE TITLE
Switch from accross to down and vice-versa

### ISSUE THREAD

**Issue by levilliard** [0xe1f/ararat#17]
After all, thanks for this great/usefull work.

I wanna know how to shitch from accross to down words and vice-versa when the user click on a button.

Thanks

**Comment by 0xe1f** [comment]
Thanks. [CrosswordView.switchWordDirection](https://github.com/0xe1f/ararat/blob/master/library/src/main/java/org/akop/ararat/view/CrosswordView.kt#L944) will do what you need.
