### ISSUE TITLE
Alphacross "notes" panel not scrollable

### ISSUE THREAD

**Issue by MIC132** [0xe1f/ararat#18]
I'm not sure if this is the right place, considering this is merely a repo for the library under alphacross, and not alphacross itself, but I think this is worth a shot.

Is the "notes" section of a crossword (the one you get by pulling the bottom bar up) not scrollable, or is this an issue on my end?
There are some crosswords (mostly imported ones) that have more text there than fits on screen, and I don't see a way to access those contents elsewhere in the app either.

If it's not an issue on my end, could it be made scrollable?

**Comment by 0xe1f** [comment]
Indeed, this repo is strictly for the library. Feel free to reach out via the GPlay Store email address. Thanks
